config/routes.rb
Planweb::Application.routes.draw do
  resources :planning_applications

  resources :web_design_assignments

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :planning_applications, only: [:create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "welcome/thank_you"
  get "welcome/login"
  get "welcome/home"
  get "welcome/about"
  get "welcome/planning"
  get "welcome/web"
  get "welcome/contact"
  get "welcome/users"
  get "users/new"

  resources :sessions

  root to: "welcome#home"

  match '/signup' => "users#new", :as => "signin"
  match '/logout' => "sessions#destroy", :as => "logout"

    root :to => "welcome#home"

end

app/models/web_design_assignment.rb
# == Schema Information
#
# Table name: web_design_assignments
#
#  id                :integer          not null, primary key
#  user_id           :integer
#  job_reference     :text
#  project_stage     :string(255)
#  issued_on         :date
#  completion_due_on :date
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class WebDesignAssignment < ActiveRecord::Base
  attr_accessible :completion_due_on, :issued_on, :job_reference, :project_stage, :user_id
  belongs_to :user
  PROJECT_STAGES = ['Prototype', '2nd Draft', '3rd Draft', 'Final Issue']

  validates :project_stage, presence: true, inclusion: {in: PROJECT_STAGES}
end

app/controllers/web_design_assignments_controller.rb
class WebDesignAssignmentsController < ApplicationController
  before_filter :signed_in_user
  # GET /web_design_assignments
  # GET /web_design_assignments.json
  def index
    if current_user.admin
      @web_design_assignments = WebDesignAssignment.all
    else
      @web_design_assignments = current_user.web_design_assignments
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @web_design_assignments }
    end
  end

  # GET /web_design_assignments/1
  # GET /web_design_assignments/1.json
  def show
    if current_user.admin
      @web_design_assignment = WebDesignAssignment.find(params[:id])
    else
      @web_design_assignment = current_user.web_design_assignments.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @web_design_assignment }
    end
  end

  # GET /web_design_assignments/new
  # GET /web_design_assignments/new.json
  def new
    @web_design_assignment = WebDesignAssignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @web_design_assignment }
    end
  end

  # GET /web_design_assignments/1/edit
  def edit
    if current_user.admin
      @web_design_assignment = WebDesignAssignment.find(params[:id])
    else
      @web_design_assignment = current_user.web_design_assignments.find(params[:id])
    end
  end

  # POST /web_design_assignments
  # POST /web_design_assignments.json
  def create
    @web_design_assignment = WebDesignAssignment.new(params[:web_design_assignment])

    respond_to do |format|
      if @web_design_assignment.save
        format.html { redirect_to @web_design_assignment, notice: 'Web design assignment was successfully created.' }
        format.json { render json: @web_design_assignment, status: :created, location: @web_design_assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @web_design_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /web_design_assignments/1
  # PUT /web_design_assignments/1.json
  def update
    if current_user.admin
      @web_design_assignment = WebDesignAssignment.find(params[:id])
    else
      @web_design_assignment = current_user.web_design_assignments.find(params[:id])
    end

    respond_to do |format|
      if @web_design_assignment.update_attributes(params[:web_design_assignment])
        format.html { redirect_to @web_design_assignment, notice: 'Web design assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @web_design_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_design_assignments/1
  # DELETE /web_design_assignments/1.json
  def destroy
    if current_user.admin
      @web_design_assignment = WebDesignAssignment.find(params[:id])
    else
      @web_design_assignment = current_user.web_design_assignments.find(params[:id])
    end

    @web_design_assignment.destroy

    respond_to do |format|
      format.html { redirect_to web_design_assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/web_design_assignments_helper.rb
module WebDesignAssignmentsHelper
end

app/views/web_design_assignments/_form.html.erb
<%= form_for(@web_design_assignment) do |f| %>
  <% if @web_design_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_design_assignment.errors.count, "error") %> prohibited this web_design_assignment from being saved:</h2>

      <ul>
      <% @web_design_assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :job_reference %><br />
    <%= f.text_area :job_reference %>
  </div>
  <div class="field">
    <%= f.label :project_stage %><br />
    <%= f.select :project_stage, WebDesignAssignment::PROJECT_STAGES %>
  </div>
  <div class="field">
    <%= f.label :issued_on %><br />
    <%= f.date_select :issued_on %>
  </div>
  <div class="field">
    <%= f.label :completion_due_on %><br />
    <%= f.date_select :completion_due_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_design_assignments/_web_design_assignment.html.erb
<li>
  <span class="content"><%= WebDesignAssignment.content %></span>
</li>

app/views/web_design_assignments/edit.html.erb
<h1>Editing a Web Design Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_design_assignment %> |
<%= link_to 'Back', web_design_assignments_path %>

app/views/web_design_assignments/index.html.erb
<h1>Web Design Assignments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Job reference</th>
    <th>Project stage</th>
    <th>Issued on</th>
    <th>Completion due on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @web_design_assignments.each do |web_design_assignment| %>
  <tr>
    <td><%= web_design_assignment.user.email %></td>
    <td><%= web_design_assignment.job_reference %></td>
    <td><%= web_design_assignment.project_stage %></td>
    <td><%= web_design_assignment.issued_on %></td>
    <td><%= web_design_assignment.completion_due_on %></td>
    <td><%= link_to 'Show', web_design_assignment %></td>
    <td><%= link_to 'Edit', edit_web_design_assignment_path(web_design_assignment) %></td>
    <td><%= link_to 'Destroy', web_design_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Web design assignment', new_web_design_assignment_path %>

app/views/web_design_assignments/new.html.erb
<h1>New Web Design Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', web_design_assignments_path %>

app/views/web_design_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @web_design_assignment.user_id %>
</p>

<p>
  <b>Job reference:</b>
  <%= @web_design_assignment.job_reference %>
</p>

<p>
  <b>Project stage:</b>
  <%= @web_design_assignment.project_stage %>
</p>

<p>
  <b>Issued on:</b>
  <%= @web_design_assignment.issued_on %>
</p>

<p>
  <b>Completion due on:</b>
  <%= @web_design_assignment.completion_due_on %>
</p>

<% if current_user.admin %>
    <%= link_to 'Edit', edit_web_design_assignment_path(@web_design_assignment) %> |
    <%= link_to 'Back', web_design_assignments_path %>
<% else %>
    <%= link_to 'back',current_user %>
<% end %>