config/routes.rb
Planweb::Application.routes.draw do
  resources :planning_applications

  resources :web_design_assignments

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :planning_applications, only: [:create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "welcome/thank_you"
  get "welcome/login"
  get "welcome/home"
  get "welcome/about"
  get "welcome/planning"
  get "welcome/web"
  get "welcome/contact"
  get "welcome/users"
  get "users/new"

  resources :sessions

  root to: "welcome#home"

  match '/signup' => "users#new", :as => "signin"
  match '/logout' => "sessions#destroy", :as => "logout"

    root :to => "welcome#home"

end

app/models/planning_application.rb
# == Schema Information
#
# Table name: planning_applications
#
#  id                                                    :integer          not null, primary key
#  user_id                                               :integer
#  planning_authority                                    :string(255)
#  planning_authority_reference                          :string(255)
#  applicant_name                                        :string(255)
#  application_type                                      :string(255)
#  location_address                                      :text
#  lodged_with_planning_authority_on                     :date
#  description                                           :text
#  validated_by_planning_authority_on                    :date
#  decision_expected_on                                  :date
#  decision_received_on                                  :date
#  decision                                              :string(255)
#  extension_requested_on                                :date
#  extension_granted_on                                  :date
#  url_to_observations                                   :string(255)
#  number_of_observations                                :integer
#  commencement_notice_received_by_planning_authority_on :date
#  commenced_on                                          :date
#  created_at                                            :datetime         not null
#  updated_at                                            :datetime         not null
#

class PlanningApplication < ActiveRecord::Base

  belongs_to :user
  attr_accessible :user_id, :applicant_name, :commenced_on, :commencement_notice_received_by_planning_authority_on, :decision, :decision_expected_on, :decision_received_on, :description, :extension_granted_on, :extension_requested_on, :location_address, :lodged_with_planning_authority_on, :number_of_observations, :planning_authority, :planning_authority_reference, :application_type, :url_to_observations, :validated_by_planning_authority_on
  validates :user_id, presence: true
end

app/controllers/planning_applications_controller.rb
class PlanningApplicationsController < ApplicationController
  before_filter :signed_in_user
  # GET /planning_applications
  # GET /planning_applications.json
  def index
    if current_user.admin
      @planning_applications = PlanningApplication.all
    else
      @planning_applications = current_user.planning_applications
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @planning_applications }
    end
  end

  # GET /planning_applications/1
  # GET /planning_applications/1.json
  def show
    if current_user.admin
      @planning_application = PlanningApplication.find(params[:id])
    else
      @planning_application = current_user.planning_applications.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @planning_application }
    end
  end

  # GET /planning_applications/new
  # GET /planning_applications/new.json
  def new
    @planning_application = PlanningApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @planning_application }
    end
  end

  # GET /planning_applications/1/edit
  def edit
    if current_user.admin
      @planning_application = PlanningApplication.find(params[:id])
    else
      @planning_application = current_user.planning_applications.find(params[:id])
    end
  end

  # POST /planning_applications
  # POST /planning_applications.json
  def create
    @planning_application = current_user.planning_applications.new(params[:planning_application])

    respond_to do |format|
      if @planning_application.save
        flash[:success] = "Planning application was successfully created"
        redirect_to root_url
      else
        render 'welcome/home'
      end
    end
  end

  # PUT /planning_applications/1
  # PUT /planning_applications/1.json
  def update
    if current_user.admin
      @planning_application = PlanningApplication.find(params[:id])
    else
      @planning_application = current_user.planning_applications.find(params[:id])
    end

    respond_to do |format|
      if @planning_application.update_attributes(params[:planning_application])
        format.html { redirect_to @planning_application, notice: 'Planning application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @planning_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planning_applications/1
  # DELETE /planning_applications/1.json
  def destroy
    if current_user.admin
      @planning_application = PlanningApplication.find(params[:id])
    else
      @planning_application = current_user.planning_applications.find(params[:id])
    end

    @planning_application.destroy

    respond_to do |format|
      format.html { redirect_to planning_applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/planning_applications_helper.rb
module PlanningApplicationsHelper
end

app/views/planning_applications/_form.html.erb
<%= form_for(@planning_application) do |f| %>
  <% if @planning_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planning_application.errors.count, "error") %> prohibited this planning_application from being saved:</h2>

      <ul>
      <% @planning_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :planning_authority %><br />
    <%= f.text_field :planning_authority %>
  </div>
  <div class="field">
    <%= f.label :planning_authority_reference %><br />
    <%= f.text_field :planning_authority_reference %>
  </div>
  <div class="field">
    <%= f.label :applicant_name %><br />
    <%= f.text_field :applicant_name %>
  </div>
  <div class="field">
    <%= f.label :application_type %><br />
    <%= f.text_field :application_type %>
  </div>
  <div class="field">
    <%= f.label :location_address %><br />
    <%= f.text_area :location_address %>
  </div>
  <div class="field">
    <%= f.label :lodged_with_planning_authority_on %><br />
    <%= f.date_select :lodged_with_planning_authority_on %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :validated_by_planning_authority_on %><br />
    <%= f.date_select :validated_by_planning_authority_on %>
  </div>
  <div class="field">
    <%= f.label :decision_expected_on %><br />
    <%= f.date_select :decision_expected_on %>
  </div>
  <div class="field">
    <%= f.label :decision_received_on %><br />
    <%= f.date_select :decision_received_on %>
  </div>
  <div class="field">
    <%= f.label :decision %><br />
    <%= f.text_field :decision %>
  </div>
  <div class="field">
    <%= f.label :extension_requested_on %><br />
    <%= f.date_select :extension_requested_on %>
  </div>
  <div class="field">
    <%= f.label :extension_granted_on %><br />
    <%= f.date_select :extension_granted_on %>
  </div>
  <div class="field">
    <%= f.label :url_to_observations %><br />
    <%= f.text_field :url_to_observations %>
  </div>
  <div class="field">
    <%= f.label :number_of_observations %><br />
    <%= f.number_field :number_of_observations %>
  </div>
  <div class="field">
    <%= f.label :commencement_notice_received_by_planning_authority_on %><br />
    <%= f.date_select :commencement_notice_received_by_planning_authority_on %>
  </div>
  <div class="field">
    <%= f.label :commenced_on %><br />
    <%= f.date_select :commenced_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planning_applications/_planning_application.html.erb
<li>
  <span class="content"><%= PlanningApplication.content %></span>
</li>

app/views/planning_applications/edit.html.erb
<h1>Editing a Planning Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @planning_application %> |
<%= link_to 'Back', planning_applications_path %>

app/views/planning_applications/index.html.erb
<small>
  <%= image_tag("PlanWeb.jpg") %>
</small>

<br/>

<h1>Planning Applications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Planning authority</th>
    <th>Planning authority reference</th>
    <th>Applicant name</th>
    <th>Application Type</th>
  </tr>

<% @planning_applications.each do |planning_application| %>
  <tr>
    <td><%= planning_application.user.email %></td>
    <td><%= planning_application.planning_authority %></td>
    <td><%= planning_application.planning_authority_reference %></td>
    <td><%= planning_application.applicant_name %></td>
    <td><%= planning_application.application_type %></td>
    <td><%= link_to 'Show', planning_application %></td>
    <% if current_user.admin %>
        <td><%= link_to 'Edit', edit_planning_application_path(planning_application) %></td>
        <td><%= link_to 'Destroy', planning_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Planning application', new_planning_application_path %>

app/views/planning_applications/new.html.erb
<h1>New planning_application</h1>

<%= render 'form' %>

<%= link_to 'Back', planning_applications_path %>

app/views/planning_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @planning_application.user_id %>
</p>

<p>
  <b>Planning authority:</b>
  <%= @planning_application.planning_authority %>
</p>

<p>
  <b>Planning authority reference:</b>
  <%= @planning_application.planning_authority_reference %>
</p>

<p>
  <b>Applicant name:</b>
  <%= @planning_application.applicant_name %>
</p>

<p>
  <b>Type:</b>
  <%= @planning_application.application_type %>
</p>

<p>
  <b>Location address:</b>
  <%= @planning_application.location_address %>
</p>

<p>
  <b>Lodged with planning authority on:</b>
  <%= @planning_application.lodged_with_planning_authority_on %>
</p>

<p>
  <b>Description:</b>
  <%= @planning_application.description %>
</p>

<p>
  <b>Validated by planning authority on:</b>
  <%= @planning_application.validated_by_planning_authority_on %>
</p>

<p>
  <b>Decision expected on:</b>
  <%= @planning_application.decision_expected_on %>
</p>

<p>
  <b>Decision received on:</b>
  <%= @planning_application.decision_received_on %>
</p>

<p>
  <b>Decision:</b>
  <%= @planning_application.decision %>
</p>

<p>
  <b>Extension requested on:</b>
  <%= @planning_application.extension_requested_on %>
</p>

<p>
  <b>Extension granted on:</b>
  <%= @planning_application.extension_granted_on %>
</p>

<p>
  <b>Url to observations:</b>
  <%= @planning_application.url_to_observations %>
</p>

<p>
  <b>Number of observations:</b>
  <%= @planning_application.number_of_observations %>
</p>

<p>
  <b>Commencement notice received by planning authority on:</b>
  <%= @planning_application.commencement_notice_received_by_planning_authority_on %>
</p>

<p>
  <b>Commenced on:</b>
  <%= @planning_application.commenced_on %>
</p>

<% if current_user.admin %>
<%= link_to 'Edit', edit_planning_application_path(@planning_application) %> |
<%= link_to 'Back', planning_applications_path %>
<% else %>
<%= link_to 'back',current_user %>
<% end %>