config/routes.rb
Planweb::Application.routes.draw do
  resources :planning_applications

  resources :web_design_assignments

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :planning_applications, only: [:create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "welcome/thank_you"
  get "welcome/login"
  get "welcome/home"
  get "welcome/about"
  get "welcome/planning"
  get "welcome/web"
  get "welcome/contact"
  get "welcome/users"
  get "users/new"

  resources :sessions

  root to: "welcome#home"

  match '/signup' => "users#new", :as => "signin"
  match '/logout' => "sessions#destroy", :as => "logout"

    root :to => "welcome#home"

end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <nav>
      <h2>PLANWEB - THE ULTIMATE IN PLANNING APPLICATION AND WEB DESIGN SERVICES</h2>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "PlanWeb", root_url, id: "logo" %>

      <nav>
        <ul class="nav pull-right">
          <button class="btn btn-link" type="button"><%= link_to "Home", root_url  %></button>
          <button class="btn btn-link" type="button"><%= link_to "About Us", :controller => "welcome", :action => "about"  %></button>


          <% if current_user %>
          <button class="btn btn-link" type="button"><%= link_to 'Planning', planning_applications_url  %></button>
          <button class="btn btn-link" type="button"><%= link_to "Web Design", web_design_assignments_url  %></button>
          <button class="btn btn-link" type="button"><%= link_to "Log Out", :controller => "welcome", :action => "thank_you"  %></button>
          <% else %>
          <button class="btn btn-link" type="button"><%= link_to 'Planning',:controller => "welcome", :action => "planning" %></button>
          <button class="btn btn-link" type="button"><%= link_to "Web Design", :controller => "welcome", :action => "web"  %></button>
          <button class="btn btn-link" type="button"><%= link_to "Sign Up", :controller => "users", :action => "new"  %></button>
          <button class="btn btn-link" type="button"><%= link_to "Sign In", :controller => "sessions", :action => "new"  %></button>
          <% end %>
          <button class="btn btn-link" type="button"><%= link_to "Contact Us", :controller => "welcome", :action => "contact"  %></button>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- Reference: http://pragprog.com/book/rails32/agile-web-development-with-rails-3-2 in PDF format saved to my laptop -->

<!DOCTYPE html>
<html>
<head>
  <title>PlanWeb</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>